version: '3'

services:
  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:23.0.2-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini
      - ./www.overloaded.conf:/usr/local/etc/php-fpm.d/www.overloaded.conf
    env_file:
      - nc.env
    depends_on:
      - redis
    networks:
      - maria
      - default

#  collabora:
#    image: collabora/code:21.11.1.0.1
#    networks:
#      - default
#      - proxy-tier
#    depends_on:
#      - web
#    cap_add:
#      - MKNOD
#    environment:
#      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
#    env_file:
#      - collabora.env

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    env_file:
      - web.env
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

volumes:
  nextcloud:

networks:
  proxy-tier:
    external:
      name: proxy-tier
  maria:
    external:
      name: maria
